version: "3"

services:
  bot:
    container_name: LemmeSmash-bot
    build: .
    entrypoint:
      - node
      - bot/main.js
    volumes:
      - "./config.json:/app/config.json:ro"
    environment:
      - TZ    # Set your timezone using Olsen naming convention, i.e. TZ=America/New_York
    depends_on:
      - db
    restart: always
  db:
    container_name: LemmeSmash-db
    image: mongo
    volumes:
      - "data:/data/db"
    restart: always

volumes:
  data:
    driver: local
