version: "2"

services:
  bot:
    container_name: lemmesmash_bot
    restart: always
    image: lemmesmash_bot:latest
    build: .
    entrypoint:
      - node
      - bot/main.js
    environment:
      - TZ=    # Set your timezone using Olsen naming convention, i.e. TZ=America/New_York
    volumes:
      - "./config.json:/app/config.json:ro"
    depends_on:
      - db
  db:
    container_name: lemmesmash_db
    restart: always
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lemmesmash
      - MONGO_INITDB_ROOT_PASSWORD=lemmesmash
      - MONGO_INITDB_DATABASE=lemmesmash
    volumes:
      - "db_data:/data/db"

volumes:
  db_data:
    driver: local